### ISSUE TITLE
"number_type" missing from the suggestions

### ISSUE THREAD

**Issue by celcius112** [ekino/jcv-idea-plugin#17]
Hello, it seems like the `number_type` validator is missing from the suggestions in https://github.com/ekino/jcv-idea-plugin/blob/master/src/main/kotlin/com/ekino/oss/jcv/idea_plugin/suggestion/ValueToDefaultValidatorsSuggestion.kt.

I could provide a PR (it looks to be a trivial issue), but I heard in my oreillette that there are some big modifications incoming, so it might be better to wait for their merge before resolving this issue.

**Comment by leomillon** [comment]
Hello @celcius112 

What do you mean by "is missing"? Because it is right there: https://github.com/ekino/jcv-idea-plugin/blob/master/src/main/kotlin/com/ekino/oss/jcv/idea_plugin/suggestion/ValueToDefaultValidatorsSuggestion.kt#L96

It is only suggested on JSON Number field values, so if you try this on a String literal value, you won't get it.

**Comment by celcius112** [comment]
right sorry, I might be blind. however the suggestion still does not appear as expected, for instance:
![Screenshot 2020-12-10 at 14 26 19](https://user-images.githubusercontent.com/1503748/101778162-c87c8600-3af3-11eb-86fa-cda655a76c5c.png)
![Screenshot 2020-12-10 at 14 26 30](https://user-images.githubusercontent.com/1503748/101778185-d16d5780-3af3-11eb-97d1-8056563b1d6f.png)
![Screenshot 2020-12-10 at 14 28 01](https://user-images.githubusercontent.com/1503748/101778268-ecd86280-3af3-11eb-9761-6e815623ee31.png)

**Comment by leomillon** [comment]
Oh right good catch!

This is indeed missing but there: https://github.com/ekino/jcv-idea-plugin/blob/master/src/main/kotlin/com/ekino/oss/jcv/idea_plugin/definition/TemplatedValidator.kt#L70

You can create a quick PR if you want it before the complete rewrite of the plugin (I cannot provide any release date right now).

**Comment by leomillon** [comment]
Waiting for JetBrains publication approval :)
